# Generated by Django 3.0.1 on 2020-01-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_phone', models.CharField(max_length=10)),
                ('c_street', models.TextField()),
                ('c_area', models.TextField()),
                ('c_city', models.TextField()),
                ('c_state', models.TextField()),
                ('c_country', models.TextField()),
                ('c_pincode', models.CharField(max_length=6)),
                ('c_website', models.URLField()),
                ('c_linkedin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50, unique=True)),
                ('c_email', models.EmailField(max_length=254)),
                ('c_password', models.CharField(max_length=16)),
                ('c_r_password', models.CharField(max_length=16)),
            ],
        ),
    ]
