# Generated by Django 3.0.1 on 2020-01-04 09:18

import Company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='c_logo',
            field=models.ImageField(blank=True, null=True, upload_to=Company.models.upload_image_path),
        ),
    ]
