# Generated by Django 3.0.1 on 2020-01-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_profile',
            name='c_email',
        ),
    ]
