# Generated by Django 3.0.1 on 2020-01-20 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_auto_20200118_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='c_verification_flag',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
