# Generated by Django 3.0.1 on 2020-01-09 10:28

import Company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_company_profile_c_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='c_logo',
            field=models.ImageField(upload_to=Company.models.upload_image_path),
        ),
    ]
