# Generated by Django 3.0.1 on 2020-02-01 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_register_c_verification_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_company_id', models.CharField(max_length=20)),
                ('p_name', models.CharField(max_length=50)),
                ('p_model_no', models.CharField(max_length=20)),
                ('p_bio', models.TextField()),
                ('p_img_1', models.ImageField(upload_to='')),
                ('p_img_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_img_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_img_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_img_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('p_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('P_warranty', models.DecimalField(decimal_places=2, max_digits=4)),
                ('p_replace_time', models.CharField(max_length=3)),
                ('p_document', models.FileField(upload_to='')),
                ('p_software_link', models.URLField(blank=True, null=True)),
                ('p_feature_1', models.CharField(max_length=300)),
                ('p_feature_2', models.CharField(max_length=300)),
                ('p_feature_3', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_4', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_5', models.CharField(blank=True, max_length=300, null=True)),
                ('p_feature_6', models.CharField(blank=True, max_length=300, null=True)),
                ('p_creation_date', models.DateTimeField(auto_now_add=True)),
                ('p_updated_date', models.DateTimeField(auto_now=True)),
                ('p_catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company.Product_Catagory')),
            ],
        ),
    ]
