# Generated by Django 3.0.1 on 2020-02-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_auto_20200201_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_hardware',
            name='p_catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Company.Product_Catagory'),
            preserve_default=False,
        ),
    ]
